name: CI para C 
on:   
  push:

jobs:
  build:
    runs-on: ubuntu-latest 
    
    steps: 
    - name: Clonar o repositório 
      uses: actions/checkout@v3 

    - name: instalar compilador GCC 
      run: sudo apt update && sudo apt install build-essential -y

    - name: Compilar o programa 
      run: gcc github.c -o programa 

    - name: Execultar o programa 
      run: ./programa 

    - name: Executar teste automizados
      run: |
        gcc -o teste teste.c
        ./teste
    
