name: CI para C

on:
  push:
    branches: 
      - main  # ou qualquer branch que deseje monitorar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar o repositório
      uses: actions/checkout@v3

    - name: Instalar compilador GCC
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Compilar o programa
      run: gcc github.c -o programa

    - name: Executar o programa
      run: ./programa

    - name: Executar testes automatizados
      run: |
        gcc -o teste teste.c
        ./teste
